name: Development Client latest e2e

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * SUN' # 0:00 AM UTC time every Sunday

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detox_latest_e2e:
    runs-on: macos-11
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v2
      - name: 🍺 Install required tools
        run: |
          brew tap wix/brew
          brew install applesimutils
          brew install watchman
          echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 💎 Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: 💎 Install cocoapods
        run: sudo gem install cocoapods
      - name: 🤖 Set up android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          avd-name: DevClientEmulator
          script: echo "expo is awesome"
      - name: 🧶 Install `expo-test-runner`
        run: |
          yarn global add expo-test-runner@$(cat package.json | grep '"expo-test-runner": "[0-9]*\.[0-9]*\.[0-9]*' | head -n 1 | awk '{print $2}' | sed 's/"//g; s/,//g')
        working-directory: packages/expo-dev-client
      - name: 🏃‍♂️ Run tests
        run: |
          yarn latest-e2e
        working-directory: packages/expo-dev-client
      - name: Store artifacts of build failures
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: expo-dev-client-latest-e2e-artifacts
          path: packages/expo-dev-client/artifacts
