
name: Docs Website Preview Closed

defaults:
  run:
    shell: bash
    working-directory: docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-preview.yml'
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  if_merged:
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-20.04
    steps:
      - name: 🪣 Delete docs preview bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: aws s3 rb s3://docs.expo.dev-pr-${{ github.event.pull_request.number }} --force && exit 0
