name: Expo Updates CLI

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/expo-updates-cli.yml
      - packages/expo-updates/cli/**
      - yarn.lock
  pull_request:
    paths:
      - .github/workflows/expo-updates-cli.yml
      - packages/expo-updates/cli/**
      - yarn.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout a ref for the event
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: ♻️ Restore workspace node modules
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            # See "workspaces" → "packages" in the root package.json for the source of truth of
            # which node_modules are affected by the root yarn.lock
            node_modules
            apps/*/node_modules
            home/node_modules
            packages/*/node_modules
            packages/@expo/*/node_modules
            packages/@unimodules/*/node_modules
            react-native-lab/react-native/node_modules
          key: ${{ runner.os }}-modules-v2-${{ hashFiles('yarn.lock') }}
      - name: 🧶 Install node modules in root dir
        run: yarn install --frozen-lockfile
      - name: Build CLI
        run: yarn build:cli
        working-directory: packages/expo-updates
      - name: Unit Test CLI
        run: yarn test:cli
        working-directory: packages/expo-updates
