name: Monorepo integrity

on:
  workflow_dispatch: {}
  push:
    branches: [master]
    paths:
      - .github/workflows/manypkg.yml
      - apps/**
      - packages/**
      - yarn.lock
  pull_request:
    paths:
      - .github/workflows/manypkg.yml
      - apps/**
      - packages/**
      - yarn.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  manypkg:
    runs-on: ubuntu-latest
    steps:
      - name: ⬢ Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17'
      - name: 👀 Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: ♻️ Restore workspace node modules
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            # See "workspaces" → "packages" in the root package.json for the source of truth of
            # which node_modules are affected by the root yarn.lock
            node_modules
            apps/*/node_modules
            home/node_modules
            packages/*/node_modules
            packages/@unimodules/*/node_modules
            react-native-lab/react-native/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: 🧶 Install node modules in root dir
        run: yarn install --frozen-lockfile
      - name: ☔️ Manypkg check
        run: yarn integrity
